### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [jasonkorolenko/teacozy#4]
Overall met expectations.

 I didn't find any major issues or errors.

My issues are about best practices in web design.  I push efficiency in your code plus in presentation to others.

Also to prepare you for the final projects, look at media queries. See if you can make this site fit inside of a mobile device by using one. You will be doing this heavily in your final projects.

https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries

https://www.w3schools.com/css/css3_mediaqueries_ex.asp

**Comment by jasonkorolenko** [comment]
Thanks much for your comments, Farish! Very helpful. I'll get started on trying to make the site responsive. ;)

Cheers!
